name: AI Test Generation and Execution

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install openai python-dotenv

    - name: Generate tests using Azure OpenAI
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      run: |
        python scripts/generate_tests.py

    - name: Run generated tests
      run: |
        pytest tests/test_generated.py --junitxml=test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml

    - name: Show test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: AI Generated Test Results
        path: test-results.xml
        reporter: junit
        fail-on-error: true
